const data = [
    {
        imgName: '162-izubr.jpg',
        gunName: '162 Изубр',
        graving_1: false,
        graving_2: false,
        graving_3: false,
        graving_4: false,
        thread_1: false,
        thread_2: false,
        thread_3: false,
        thread_4: false,
        inscriptions_1: false,
        inscriptions_2: false,
        modification_1: false,
        modification_2: false,
        price: 32950,
        graving_cost: 7350,
        thread_cost: 4900,
        inscriptions_cost: 2500,
        modification_cost: 1600,
    },
    {
        imgName: 'mr-156.jpg',
        gunName: 'МР-156',
        graving_1: false,
        graving_2: false,
        graving_3: false,
        graving_4: false,
        thread_1: false,
        thread_2: false,
        thread_3: false,
        thread_4: false,
        inscriptions_1: false,
        inscriptions_2: false,
        modification_1: false,
        modification_2: false,
        price: 46500,
        graving_cost: 7350,
        thread_cost: 4900,
        inscriptions_cost: 2500,
        modification_cost: 1600,
    },
    {
        imgName: 'saiga-7.62.jpg',
        gunName: 'Сайга 7.62',
        graving_1: false,
        graving_2: false,
        graving_3: false,
        graving_4: false,
        thread_1: false,
        thread_2: false,
        thread_3: false,
        thread_4: false,
        inscriptions_1: false,
        inscriptions_2: false,
        modification_1: false,
        modification_2: false,
        price: 29325,
        graving_cost: 7350,
        thread_cost: 4900,
        inscriptions_cost: 2500,
        modification_cost: 1600,
    }
]

export default data